services:
  mongo:
    image: mongo
    container_name: mongo_local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo-data:/data/db
      - ./scripts/seed_mongo.js:/docker-entrypoint-initdb.d/seed_mongo.js # Mount for seeding

  backend:
    build: .
    container_name: go_ecommerce
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/ecommerce"

volumes:
  mongo-data:
